site_name: RHDH Blueprints Documentation
site_description: Documentation for Red Hat Developer Hub Blueprints

repo_url: https://github.com/your-org/rhdh-blueprints-doc
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Blueprints:
      - Overview: blueprints/overview.md
      - Creating Blueprints: blueprints/creating.md
      - Using Blueprints: blueprints/using.md
  - Reference:
      - Configuration: reference/configuration.md
      - API: reference/api.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables


